### ISSUE TITLE
Login and Password for Unraid Version 

### ISSUE THREAD

**Issue by jimb2834** [diskoverdata/diskover-community#104]
Hi, 

Wanted to try Diskover as an alternative to building an indexer. I can reach the Login screen but no login and password works

Tried, user=diskover with password=darkdata 
but nothing.

May I ask how to login ?

**Comment by mrinc** [comment]
Ref: [https://docs.linuxserver.io/images/docker-diskover](https://docs.linuxserver.io/images/docker-diskover)  

Default Username: `diskover`  
Default Password: `darkdata`

**Comment by shirosaidev** [comment]
on first set up/login, you'll be asked to change your password from default (default password found in Constants.php), and that password will get stored in diskoverdb.sqlite3. If you forgot your password, delete that db file and try to login again.
