### ISSUE TITLE
illegal character?

### ISSUE THREAD

**Issue by maxvaneck** [diskoverdata/diskover-community#106]
hi there , i'm using unraid mainly for media and the occasional other shennanigans . i'm using the linuxserver.io docker and i'm getting an  error  when running the first crawl 
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Unknown tokenizer type [char_group] for [path_tokenizer]')

after some googling this looks like elasticsearch or diskover are tripping over  characters it doesn't know what to do with 
i have anime in my media collection so i'm guessing it is japanese characters . sonarr and radarr are both set to replace illegal characters so i doný know what's going on here

**Comment by shirosaidev** [comment]
@maxvaneck check you are using Elasticsearch 7.x

**Comment by maxvaneck** [comment]
no i'm using  elasticsearch 5.6.14 because this page told me it only works using 5.x
https://www.linuxserver.io/blog/2019-06-28-getting-started-with-diskover-in-docker
in hindsight the blogpost is kinda old
will try with latest elasticsearch

**Comment by shirosaidev** [comment]
for diskover CE v2, you need to use ES 7.x, ES 5.x is not supported

**Comment by maxvaneck** [comment]
as it turns out you were correct . it works fine with 7.10.2 .  sorry for the late reply but school got in the way and i accidently installed the wrong elasticsearch docker again
