### ISSUE TITLE
Tolerate not being able to connect to server?

### ISSUE THREAD

**Issue by axfelix** [diskoverdata/diskover-community#39]
Hi,

I'm interested in being able to deploy the diskover client (i.e. the worker and the crawlers) separately from the diskover-web stack (redis, ES, and the PHP app), but as far as I can tell, the worker bots currently have no way of tolerating the server going away by e.g. queueing up POSTs and trying again on a timer or when the network environment changes. Is that true? Would there be plans to change this?

Thanks!

**Comment by shirosaidev** [comment]
diskover can be separate from diskover-web. diskover requires Elasticsearch and Redis, but those also could be installed on separate hosts or in their own docker container. diskover-web requires just php and ideally nginx or apache. diskover-web also needs a connection to that same Elasticsearch where the indices are that get created by diskover. worker bots (which are different than diskover tree walk client), can be on any host in your network, they are not required to be on diskover or diskover-web host. They just require connections to the same redis and elasticsearch as diskover.py.
