### ISSUE TITLE
possible to ignore hardlinks

### ISSUE THREAD

**Issue by mathse** [diskoverdata/diskover-community#50]
is it possible to ignore the hardlinks?

I have a massive file share with 70 million files in it.
`find /path -type f`
takes around 12 hours to finish

diskover will simply stall after roughly one hour with aprox 50-60 million files
at this point it already found 141,748 hardlinks
the scan simply halts at "/ Crawling (Queue: 0, 1450.5 dirs/sec)" and sits there for days (i let it run the whole weekend)

i did a test with simply
`diskover.py -i diskover-index-d4 -d /path/ -M 4`
and it stalls with
`/ Crawling (Queue: 0, 1450.5 dirs/sec) Elapsed Time: 0:01:04` (4 hardlinks so far)

I tried another share on the same fileserver (both connected via nfs) without a problem, but this share does not have any hardlinks
all other scans i did before never had any hardlinks

**Comment by shirosaidev** [comment]
I don't think hardlinks is the issue here. You said that it takes 1 hour for diskover to index 50-60 million files in that share and the total amount of files is 70 million? Is that correct?
How soon in the crawl does it start showing Queue: 0? Are there any jobs in the queue or any bots busy in rq or rq-dashboard when it's sitting at Queue: 0?

**Comment by shirosaidev** [comment]
I've pushed some updated to rc28 for printing out the directories being processed by treewalk/scandirwalk. Can you update to latest and crawl again using --verbose or --debug and reply with the last 10 lines of output before it gets "stuck"? Also during that time is there any jobs in rq and any bots busy?

**Comment by shirosaidev** [comment]
message me on linuxserver.io discord @shirosai

**Comment by mathse** [comment]
for anyone following: it has nothing to do with the hardlinks but with the number of files some directories - looks like 300K+ files in one single dir is simply to much

**Comment by shirosaidev** [comment]
did running with --dirsonly work? That will stop the files from getting sent to redis/rq and get the bots to scandir the files in the directories sent to them.
