### ISSUE TITLE
Change Base URL

### ISSUE THREAD

**Issue by archeious** [diskoverdata/diskover-community#59]
How can I change the href base url?  I have it setup behind a reverse proxy (e.g. www.domain.tld/diskover)  but it fails because the urls are all absolute to the url.

**Comment by shirosaidev** [comment]
in diskover-web all the url's are relative, not absolute. Did you make a symlink dashboard.php -> index.php ?

**Comment by shirosaidev** [comment]
@archeious did you get this working?

**Comment by ravensorb** [comment]
I too would appreciate it if there was a way to set the base url -- I am trying to run this behind a proxy and need to run it in a subpath (ex: /diskover).

Note: Looking at the code almost all of the URLs start is "/" which would make this absolutely correct?  Maybe a simple inject of the base href tag could help (https://html.com/attributes/base-href/)

**Comment by CMclarty** [comment]
hello @shirosaidev. I'm in the same situation as @archeious. 

I ran` `ln -sf dashboard.php index.php`` in the docker container;

```
root@cee647d5ddaf:/app/diskover-web/public# ls -al index.php 
lrwxrwxrwx 1 root root 13 Aug 19 10:31 index.php -> dashboard.php
```

 to link the index.php to to the dashboard, but hitting xxx.com/diskover still redirects to xxx.com. May be a stupid error on my part. My host nginx location:

```
     location /diskover/ {
          proxy_pass http://127.0.0.1:<portnumber>/diskover/;
     }
```

Thanks for creating diskover.

**Comment by ChristopherMillon** [comment]
Any news about this? Can't use diskover if I can't setup a base url
