### ISSUE TITLE
Question about diskover and treewalk client functionality.

### ISSUE THREAD

**Issue by svavaroe** [diskoverdata/diskover-community#60]
I wanted to ask you some
questions tho about it's functionality which I can't seem to find any information on.

Firstly, my current setup is that I have some linux file servers and OS X servers.
They host different data, and are not connected in any way into a SAN or something like that.
They share the same DMZ and share out different volumes and data.

I have configured a server that hosts elasticsearch, redis and also diskover.
That same server host also the diskover-web frontent.

Now, as I'm really interested in the diskover-treewalk-client.

In my scenario above would I need to create different indexes for every server that's going
to use the treewalk-client? Is it a requirement for the diskover server to also have the same mount points and data paths as treewalk-clients have?
regarding -r and -R option.

For an example, server #1 has data files on /mnt/iscsivol01.
But the diskover server does not have this mountpoint and or data.

diskover-treewalk-client.py -p diskover_server -t metaspider -r /mnt/iscsivol01 -R ?

So my scenario is that diskover server does not know and or see any of those mountpoints for all these servers.
I would much like to host my diskover server in the cloud and use the treewalk-client as much as possible.

And final question, is it normal for the diskover.py with the "-L" argument to exit after 
crawling for a treewalk-client? So in theory I have to manually execute "-L" diskover.py every-time I want my treewalk-client to process data to the diskover server ?

(diskover server)
Waiting for connection, listening on xxx.xxx.xxx.xxx port 9998 TCP (ctrl-c to shutdown)

(treewalk client)
python3 diskover-treewalk-client.py -p diskover_server -t metaspider -r /mnt/iscsivol01 -R /data

(diskover server after successful connection and process)
2019-04-03 13:06:52,666 [INFO][diskover] Finished calculating 6436 directory sizes in 0d:0h:00m:41s
2019-04-03 13:06:52,671 [INFO][diskover] Setting ES index settings back to defaults
2019-04-03 13:06:52,691 [INFO][diskover] Force merging ES index...
2019-04-03 13:06:52,922 [INFO][diskover] All DONE! Sayonara!
exit

Thank you kindly.
Best regards,
Svavar O - Reykjavik - Iceland

**Comment by shirosaidev** [comment]
diskover.py running in proxy mode (-L) needs a mount to determine the total/used size of the filesystem being crawled. You could use an sshfs mount, see here for more info https://github.com/shirosaidev/diskover-treewalk-client

diskover.py proxy can have different mount points then the diskover crawler/bots, see above for more info regarding -r and -R.

diskover.py proxy currently automatically exits after the crawl is finished calculating directory sizes.
