### ISSUE TITLE
Request: Option to use only the file size for finddupes

### ISSUE THREAD

**Issue by sarbian** [diskoverdata/diskover-community#71]
The current md5 hash used for finddupes uses the file size and mtime. It works fine for some case but it does not detect dupe that have different mtime. 
Could you add either:
- an option that would change how the md5 is build 
- or add a second md5 that uses only the file size and an option to use this one for the finddupes check

It may be a lot slower but would provide far better result for my uses.

**Comment by shirosaidev** [comment]
this has been added to latest version https://github.com/shirosaidev/diskover/blob/master/CHANGELOG.md
