### ISSUE TITLE
Request: Need NFS disk crawl benchmark results

### ISSUE THREAD

**Issue by sumesh6677** [diskoverdata/diskover-community#76]
Hello,

My requirement is to crawl NFS mounted disks and when i ran it on a directory (size 110 TB), the crawl ran more than 2 days and still didn't complete. I have followed all the optimization instructions mentioned in your website for Elasticsearch & redis

Verified the queue status in Redis from the RQ dashboard and it seemed to process all jobs quickly. I had started 40 worker bots and most of the time, 39 were seen to be in idle state. So i assume that whatever requests are being pulled are 

Running it on a linux machine (Centos 7.5). Its hardware configuration is as below:
Architecture: x86_64
CPU(s): 12
Model name: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
RAM: 32 GB

The crawl command that i am using is:
python diskover.py -i diskover-i1 -d /my/path -e -a -S -T 50

So could you please share any benchmark results for NFS disks if you have any? Kindly let me know if you have any improvements/suggestions for the crawl i am launching .

**Comment by sumesh6677** [comment]
For to mention that the diskover setup was done via docker.

**Comment by shirosaidev** [comment]
Try with default walk threads (default is cpu cores x 2 OR don't use -T OR
set -T to a lower number like 12), use 16 workers and see if your
performance improves. You might be over-saturating that nfs link with too
many crawl threads and bots on that single host. Check that ES is on fast
disk, preferably ssd, and set ES to use 16 GB java heap size (memory).

**Comment by shirosaidev** [comment]
Try with default walk threads (default is cpu cores x 2 OR don't use -T OR set -T to a lower number like 12), use 16 workers and see if your performance improves. You might be over-saturating that nfs link with too many crawl threads and bots on that single host. Check that ES is on fast disk, preferably ssd, and set ES to use 16 GB java heap size (memory).

**Comment by shirosaidev** [comment]
Crawling that little data should not take anywhere near 2 days, should be easy to crawl it in under a few hours. What type of nfs storage? What is the network connection speed/latency between the diskover host and the nfs disk?

**Comment by sumesh6677** [comment]
Thank you so much for your valuable feedback. I do see some improvements with the options you suggested. I ran the trawl on a disk (8.54 TB), it took just 10 minutes.
But when i initiated a trawl on another disk path (same NFS network) with size 124 TB, it has still not finished even after  2 hours. The only difference that i can see is that several of the directories have lots of files in them (counting up to 10,000 or some perhaps having 15,000)

As you had asked, the latency is as below:
32212254720 bytes (32 GB, 30 GiB) copied, 282.795 s, 114 MB/s

NFS version: 4.0

Also forgot to mention that i am using Diskover version - 1.5.0.8

**Comment by sumesh6677** [comment]
Also, the heap size allocated was 16 GB for Elasticsearch - which i remember was mentioned in the Hardware Optimization instructions. ES index is located on a locally mounted disk.

**Comment by sumesh6677** [comment]
Hello,
I was trying multiple trawls on our hard-drives and would like to share the results for your reference. Looks like the trawl is taking a considerable amount of time if the directories have large no. of files. But astonishingly, the threads don't seem to manage the work load amongst them. This i observed when i ran the trawls (in debug mode), the threads seem to be idle most of the time. Even the worker bots.

Directory size	Sub-Directory count	   File count	Trawl time
24 Tb	         96050	                   23658637	3h:41m:00s
54.8 Tb	         526101	                   72918615	18 hrs and still running
10.6 Tb	         13278319	           56938	        2h:27m and still running
121 Gb	         7300	                   82024	        01m:27s
314 Gb	         10974	                   17637	        0m:13s
566 Gb	         25538	                   24524	        12s
1.26 Tb	         12891	                   90606	        17s
2.56 Tb	         11519	                   232623	        46m:56s

The trawls were run from a docker container with the Diskover version. 1.5.0.8

Since the disks that i am using are having millions of files, i believe the trawls would not get over in a 5 hour window. Since we are using a heavy data centric solutuion, we can expect a considerable amount of data culls and data additions. The kind of statistics which i was looking at was a directory specific one. If i have information pertaining to directories only, i believe that works very much for me. Is it possible to capture only directory stats - like directory size, parent directory path, last accessed time, last modified time, creation time, recursive file count list, recursive directory count list? With this kind of approach, we can save a lot of time doing trawls. 

I looked at the Diskover command-line options but did not get any. Is it possible for you to provide a feature for directories only?  So that means, after the crawl, i get to see all the directories with their respective attributes?

I will try to capture few more trawl results and share it with you. All the results shown above were run with the options like:
python diskover.py -i <index-name> -d <directory-path> -e -a -S

No. of worker bots used: 16
The NFS network/disk latency - 750 Mb/s
Elasticsearch index disk - local

Appreciate your help in this matter! Thanks!!

**Comment by shirosaidev** [comment]
try crawling with nfs v3 and making sure that you are using rdirplus (readdirplus) nfs client option

**Comment by sumesh6677** [comment]
Thanks for these pointers!!

But these options didn't help us with the crawling speed. Infact, it is taking more time with nfs v3 (and readdirplus option enabled). We are observing that when it tried to crawl a directory with large number of files (lets say a million files), the crawl just stops. The worker bots seem to be idle as i am parallelly monitoring it in the RQ dashboard.

Wanted to check with you on one more point - how do we arrive at a figure for the no. of worker bots to be used? Based on the disk size? So for most of the crawls that i am performing, i am using 16.

So looking at the results, Diskover doesn't seem to be the right fit for our Disk Usage analysis setup. If we were to trawl a 2 Petabyte  of disk, i am not sure it is a feasible option. There may be millions of files in the disk and gathering information of all of them would definitely consume time.

Hence, i had asked you if there was an option in Diskover to gather only directory related information. It would be a very nice feature to have, actually.

**Comment by shirosaidev** [comment]
Worker bots you can set to number of cpu cores on the diskover host x 2 is usually around the best number. Bots will be idle if the diskover.py crawler cannot access directory lists fast enough over your network mount or it hits a directory with a ton of file this can happen. What do you have set to walk threads (-T flag) for diskover.py and how many cpu cores on the diskover host?

Try running diskover with  `--dirsonly` flag https://github.com/shirosaidev/diskover/wiki/CLI-options

**Comment by sumesh6677** [comment]
Thanks for your prompt reply!!

I had tried with 8, 16 as well as the (host x 2 cpu cores) worker bots. But in all cases i can see the worker bots are idle when it encounters a directory with huge amount of files (in my case 10 - 22 million).  Also, the -T flag is something which i did experiment with. It is not aiding me with the trawls.

As i had mentioned earlier, the cpu cores that i am having is 12, so with many times with default run it has taken 24 bots. 

For the --dirsonly option, it didn't help much with the trawls. An initial look at the run made me think that only directories are being scanned but in the end, i could see files also being added in Elasticsearch. As stated earlier, this tool would have been a perfect match if it provided an option of  capturing only directory information.

Our requirement is primarily meant for a corporate purpose where we would need daily scans of the filesystem and the operations team is notified about the delta changes with culls and other day to day workflows run on the disks to keep track of the growing disk size. 

Just to give you an update, we are using OneFs for managing the Dell Isilon cluster of disks running on NFS4

**Comment by shirosaidev** [comment]
If bots are idle, lower your batch size using -b N, the default is 50 dirs per batch. You can also adjust the auto batch size for min and max in diskover config file and use -a.

**Comment by sumesh6677** [comment]
We did try altering the min and max values in diskover.cfg and provided the '-a' option is the trawls, but the trawls are still taking a considerable amount of time. For example, to trawl a 12.1 Tb of directory, it took 10h:35m. But the file-count was 13,829,183 and directory-count 45,446

**Comment by shirosaidev** [comment]
please try the new --splitfiles feature in latest release v1.5.0.10, this will distribute the meta collecting of files for directories with many files https://github.com/shirosaidev/diskover/blob/master/CHANGELOG.md
