### ISSUE TITLE
Unable to get NTFS file owner

### ISSUE THREAD

**Issue by raychankit** [diskoverdata/diskover-community#80]
I run diskover in Docker. Because the diskover container is linux-base, I'm not able to get the NTFS file owner when I scan my NetApp CIFS shares. I tried different ways but in vain.

I tried:
- Docker volume
- Mount using CIFS with Kerberos
- Mount using CIFS with Windows a/c

Is there any way to get NTFS owner when we scan CIFS shares?

**Comment by varontron** [comment]
@raychankit did you ever get this to work?  Following the somewhat sparse instructions in the wiki and linked documentation did not lead to a happy place.
