### ISSUE TITLE
Elasticsearch 5.6.x EOL, support maintained version of Elastic in Community

### ISSUE THREAD

**Issue by kittydoor** [diskoverdata/diskover-community#87]
Elasticsearch publishes version End of Life dates on their webstie.

https://www.elastic.co/support/eol

Version 5.6.x has been End of Life since 2019-03-11 / release of 7.0. You can read more about their maintenance policy in the link above.

This project appears to have a hard dependency on 5.6.x, and ideally it should be updated to support Elasticsearch 7 by default in the community edition too.

Tags: es5 es5.6 es7

**Comment by shirosaidev** [comment]
Diskover v2 community is being worked on and hopefully will be released in Q1 2021. It will support ES 7.x.

**Comment by techie2000** [comment]
> Diskover v2 community is being worked on and hopefully will be released in Q1 2021. It will support ES 7.x.

Is there a revised eta of v2 (as we are now approaching mid-Q2)?

**Comment by shirosaidev** [comment]
We are hoping to be out of beta and into release candidate in the next month or so with v2.0 out early this summer. Stay tuned for more info and join the diskover Slack for more updates.
