### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by zidingz** [diskoverdata/diskover-community#95]
Hey there!

I belong to an open source security research community, and a member (@leommjr) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by shirosaidev** [comment]
https://github.com/diskoverdata/diskover-community/blob/master/SECURITY.md

**Comment by JamieSlome** [comment]
@shirosaidev - it looks like we sent an e-mail about 5 months ago to the `info@...` address. I will re-send to the address referenced in your `SECURITY` policy.

Just for ease, the report can be accessed here:
https://huntr.dev/bounties/12a70e45-dfe0-42c2-a52d-fdc23213028a/

It is private and only accessible to maintainers with repository write permissions 👍
