### ISSUE TITLE
diskover ce v2.0-rc.4 unusable -- 500 error after login

### ISSUE THREAD

**Issue by rsulliv1** [diskoverdata/diskover-community#98]
valid credentials or not, either way the login page redirects to a 500 error. nothing thrown to container log.

Confirmed with another user via Discord.

had to pull docker image with this tag in order to get past this issue: lscr.io/linuxserver/diskover:version-v2.0-rc.3 

** assuming this issue is with the release and not the docker package!

**Comment by shirosaidev** [comment]
It appears to be a lsio docker container issue, php is missing sqlite3 extension which is now required in rc4, a db file gets created to store encrypted diskover user password in web root named diskoverdb.sqlite3.
https://discord.com/channels/354974912613449730/506925392603512839/945989781152743444

Forwarded this onto the lsio dev who looks after the docker container.

Appears to be another issue with the container as well:
https://discord.com/channels/354974912613449730/506925392603512839/946602422439137310

**Comment by rsulliv1** [comment]
That is for the update! I posted something to them as well.

On Feb 24, 2022, 23:51, at 23:51, Chris Park ***@***.***> wrote:
>It appears to be a lsio docker container issue, php is missing sqlite3
>extension which is now required in rc4, a db file gets created to store
>encrypted diskover user password in web root named diskoverdb.sqlite3.
>https://discord.com/channels/354974912613449730/506925392603512839/945989781152743444
>
>Forwarded this onto the lsio dev who looks after the docker container.
>
>Appears to be another issue with the container as well:
>https://discord.com/channels/354974912613449730/506925392603512839/946602422439137310
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/diskoverdata/diskover-community/issues/98#issuecomment-1050547380
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by shirosaidev** [comment]
lsio updated the docker container to include php sqlite
