### ISSUE TITLE
database location & persistence suggestion

### ISSUE THREAD

**Issue by martadinata666** [diskoverdata/diskover-community#99]
As database from new installation doesn't exist, diskover will create one after setup at `/web/root/diskoverdb.sqlite3` or manually `touch` first. My suggestion is move `diskoverdb.sqlite3` to it own directory like `/web/root/database/diskoverdb.sqlite3`. My reason is on docker installation web root mostly wiped and replaced new, with usage of `database` dir db stored it own directory then we can use `database/` volume mount instead of mount/linking database directly. 
Hacky way:
```
volumes:
  ./diskoverdb.sqlite3:/web/root/diskoverdb.sqlite3
```
or like this pull https://github.com/linuxserver/docker-diskover/pull/51
```
if [[ ! -e "/config/diskoverdb.sqlite3" ]]; then
    touch /config/diskoverdb.sqlite3
fi
ln -sf /config/diskoverdb.sqlite3 /app/www/diskoverdb.sqlite3
```

Prefered way:
```
volumes:
  ./database:/web/root/database
```

**Comment by shirosaidev** [comment]
rc5 has a new DATABASE config setting to set the database path
